name: Coverage Report Fun Olympics
on:
    push:
        branches: [main]
jobs:
    coverage:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v1
            - name: Coverage Report using ArtiomTr/jest-coverage-report-action
            - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 80 # optional parameter